  0%|                                                   | 0/80 [00:00<?, ?it/s]Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fb544fbd040>
0 25113 0.4519267678260803
1 25113 0.5450525283813477
2 25113 0.45676034688949585
3 25113 0.473465234041214
4 25113 0.4353749752044678
5 25113 0.3528118431568146
6 25113 0.4989318251609802
7 25113 0.36978021264076233
8 25113 0.3712695240974426
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1510, in __del__
    self._shutdown_workers()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1456, in _shutdown_workers
    self._pin_memory_thread.join()
  File "/usr/local/lib/python3.9/threading.py", line 1053, in join
    self._wait_for_tstate_lock()
  File "/usr/local/lib/python3.9/threading.py", line 1073, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
  0%|                                                   | 0/80 [00:32<?, ?it/s]
Traceback (most recent call last):
  File "/code/RLoc/training/train.py", line 31, in <module>
    do_train(params, debug=args.debug, device=device)
  File "/code/RLoc/training/trainer.py", line 410, in do_train
    torch.cuda.empty_cache()
  File "/usr/local/lib/python3.9/site-packages/torch/cuda/memory.py", line 121, in empty_cache
    torch._C._cuda_emptyCache()
KeyboardInterrupt
