  0%|                                                   | 0/50 [00:12<?, ?it/s]
Traceback (most recent call last):
  File "/code/RLoc/training/train.py", line 31, in <module>
    do_train(params, debug=args.debug, device=device)
  File "/code/RLoc/training/trainer.py", line 398, in do_train
    loss, temp_stats, _ = loss_fn(vladQ, vladP, vladN,  sim_p, sim_n)
  File "/code/RLoc/models/loss.py", line 382, in __call__
    pos_dist = self.distance(vladQ[b:b+1], vladP[b])  # [n_pos]
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pytorch_metric_learning/distances/base_distance.py", line 28, in forward
    mat = self.compute_mat(query_emb_normalized, ref_emb_normalized)
  File "/usr/local/lib/python3.9/site-packages/pytorch_metric_learning/distances/lp_distance.py", line 24, in compute_mat
    return torch.cdist(query_emb, ref_emb, p=self.p)
  File "/usr/local/lib/python3.9/site-packages/torch/functional.py", line 1183, in cdist
    return _VF.cdist(x1, x2, p, None)  # type: ignore[attr-defined]
RuntimeError: X1 and X2 must have the same number of columns. X1: 2 X2: 512
